//
// AuthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResponse: Codable, JSONEncodable, Hashable {

    public enum TokenType: String, Codable, CaseIterable {
        case bearer = "bearer"
    }
    /** The JWT token for authenticating subsequent API requests */
    public var accessToken: String
    public var tokenType: TokenType = .bearer
    /** Token expiry time in seconds */
    public var expiresIn: Int?
    public var user: AuthResponseUser

    public init(accessToken: String, tokenType: TokenType = .bearer, expiresIn: Int? = nil, user: AuthResponseUser) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(tokenType, forKey: .tokenType)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encode(user, forKey: .user)
    }
}

