//
// AuthResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResponseUser: Codable, JSONEncodable, Hashable {

    /** Unique internal user ID */
    public var userId: String
    public var email: String
    /** User's full name from Google */
    public var name: String?
    /** URL to user's profile picture from Google */
    public var picture: String?

    public init(userId: String, email: String, name: String? = nil, picture: String? = nil) {
        self.userId = userId
        self.email = email
        self.name = name
        self.picture = picture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case email
        case name
        case picture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(picture, forKey: .picture)
    }
}

