//
// EnhancementAudioResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnhancementAudioResponse: Codable, JSONEncodable, Hashable {

    public enum AudioFormat: String, Codable, CaseIterable {
        case mp3 = "mp3"
    }
    /** Base64 encoded MP3 audio data */
    public var audioBase64: Data
    /** The format of the audio data */
    public var audioFormat: AudioFormat

    public init(audioBase64: Data, audioFormat: AudioFormat) {
        self.audioBase64 = audioBase64
        self.audioFormat = audioFormat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audioBase64 = "audio_base64"
        case audioFormat = "audio_format"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audioBase64, forKey: .audioBase64)
        try container.encode(audioFormat, forKey: .audioFormat)
    }
}

