//
// GetEnhancements200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetEnhancements200Response: Codable, JSONEncodable, Hashable {

    public var total: Int
    public var items: [EnhancementSummary]

    public init(total: Int, items: [EnhancementSummary]) {
        self.total = total
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(items, forKey: .items)
    }
}

