//
// GetHealth200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetHealth200Response: Codable, JSONEncodable, Hashable {

    public var status: String
    public var timestamp: Date

    public init(status: String, timestamp: Date) {
        self.status = status
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

