//
// GoogleAuthRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GoogleAuthRequest: Codable, JSONEncodable, Hashable {

    /** Google ID token obtained from the iOS client */
    public var idToken: String

    public init(idToken: String) {
        self.idToken = idToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case idToken = "id_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(idToken, forKey: .idToken)
    }
}

