//
// ReadinessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReadinessResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case ready = "ready"
        case notReady = "not_ready"
    }
    public var status: Status
    public var services: ReadinessResponseServices

    public init(status: Status, services: ReadinessResponseServices) {
        self.status = status
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(services, forKey: .services)
    }
}

