//
// ReadinessResponseServices.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReadinessResponseServices: Codable, JSONEncodable, Hashable {

    public var gemini: Bool?
    public var tts: Bool?
    public var database: Bool?

    public init(gemini: Bool? = nil, tts: Bool? = nil, database: Bool? = nil) {
        self.gemini = gemini
        self.tts = tts
        self.database = database
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gemini
        case tts
        case database
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gemini, forKey: .gemini)
        try container.encodeIfPresent(tts, forKey: .tts)
        try container.encodeIfPresent(database, forKey: .database)
    }
}

