//
// ValidationErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidationErrorResponse: Codable, JSONEncodable, Hashable {

    public enum ModelError: String, Codable, CaseIterable {
        case validationError = "VALIDATION_ERROR"
    }
    public var error: ModelError
    public var message: String
    public var validationErrors: [ValidationErrorResponseValidationErrorsInner]

    public init(error: ModelError, message: String, validationErrors: [ValidationErrorResponseValidationErrorsInner]) {
        self.error = error
        self.message = message
        self.validationErrors = validationErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case message
        case validationErrors = "validation_errors"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encode(message, forKey: .message)
        try container.encode(validationErrors, forKey: .validationErrors)
    }
}

